"""added added_by fi

Revision ID: 604fd6bcd21a
Revises: 
Create Date: 2023-10-07 21:48:17.694929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604fd6bcd21a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=128), nullable=False),
    sa.Column('column', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('column')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
